COMMON_OBJS = timer.o dummy.o
COMMON_LIBS = -lrt

timer.o:
	$(CXX) $(CXXFLAGS) -c $(COMMON)/timer.cpp -o timer.o
	$(CXX) -MM $(CXXFLAGS) $(COMMON)/timer.cpp > timer.d

dummy.o:
	$(CXX) $(CXXFLAGS) -c $(COMMON)/dummy.cpp -o dummy.o
	$(CXX) -MM $(CXXFLAGS) $(COMMON)/dummy.cpp > dummy.d

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<
	$(CXX) -MM $(CXXFLAGS) $< > $*.d

%.o: %.c
	$(CC) $(CFLAGS) -c $<
	$(CC) -MM $(CFLAGS) $< > $*.d

clean_common:
	/bin/rm -fv $(COMMON_OBJS)
