COMMON_OBJS = timer_impl.o
COMMON_LIBS = -lrt
COMMON_DEPS = $(COMMON_OBJS:.o=.d)

-include $(COMMON_DEPS)

timer.o:
	$(CXX) $(CXXFLAGS) -c $(COMMON)/timer_impl.cpp -o timer_impl.o
	$(CXX) -MM $(CXXFLAGS) $(COMMON)/timer_impl.cpp > timer_impl.d

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<
	$(CXX) -MM $(CXXFLAGS) $< > $*.d

%.o: %.c
	$(CC) $(CFLAGS) -c $<
	$(CC) -MM $(CFLAGS) $< > $*.d

clean_common:
	/bin/rm -fv $(COMMON_OBJS) $(COMMON_DEPS)
